// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrswfqezcdkqvpulikug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yc3dmcWV6Y2RrcXZwdWxpa3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjAwNjMsImV4cCI6MjA1OTkzNjA2M30.ZYTPyR5cUiZsqEslhnt4AG4yLFfElOsqMHRD_ZU2sd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);